blog/urls.py
from django.urls import path

from . import views

app_name = "blog"
urlpatterns = [
    path('', views.ArticleListView.as_view(), name='home'),
    path('page/<int:page>', views.ArticleListView.as_view(), name='home'),
    path('article_detail/<slug:slug>/', views.ArticleDetailView.as_view(), name='article_detail'),
    path('category/<slug:slug>/', views.CategoryListView.as_view(), name='category'),
    path('category/<slug:slug>/page/<int:page>', views.CategoryListView.as_view(), name='category'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from blog import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from extensions.utils import jalali_convertor
#My-Manager

class ArticleManager(models.Manager):
    def published(self):
        return self.filter(status="p")

    # def get_queryset(self):
    #     return super().get_queryset().filter(status='p')

class CategoryManager(models.Manager):
    def published(self):
        return self.filter(status=True)

#Mt-Models
class Article(models.Model):
    objects = ArticleManager()


    class Meta:
        verbose_name = 'مقاله'
        verbose_name_plural = 'مقالات'
        ordering = ('-published',)

    STATUS_CHOICES = (
        ('d', 'پیش نویس'),
        ('p', 'منتشر شده '),
    )

    title = models.CharField(max_length=100, verbose_name='عنوان مقاله')
    slug = models.SlugField(max_length=100, unique=True, verbose_name='توضیحات')
    category = models.ManyToManyField('Category', related_name='article', verbose_name= 'دسته بندی')
    descriptions = models.TextField(verbose_name='آدرس مقاله')
    thumbnail = models.ImageField(upload_to="images", verbose_name='تصویر')
    published = models.DateTimeField(default=timezone.now, verbose_name='زمان انتشار')
    created = models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')
    updated = models.DateTimeField(auto_now=True, verbose_name='زمان وآخرین ویرایش')
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, verbose_name='وضعیت انتشار')


    def __str__(self):
        return self.title

    def jalali_published(self):
        return jalali_convertor(self.published)

    jalali_published.short_description = "زمان انتشار"

    def category_published(self):
        return self.category.filter(status=True)



    def image_tag(self):
        from django.utils.html import format_html
        return format_html('<img style="border-radius :3px" src="%s" width="100" height="75" />' % (self.thumbnail.url))
    image_tag.short_description = 'عکس'



class Category(models.Model):
    parent = models.ForeignKey('self',default=None , related_name='children', null=True, blank=True,
                                on_delete=models.SET_NULL, verbose_name='زیردسته')
    title = models.CharField(max_length=100, verbose_name='عنوان دسته بندی')
    slug = models.SlugField(max_length=100, unique=True, verbose_name='توضیحات')
    status = models.BooleanField(default=True, verbose_name='آیا نشان داده شود ؟')
    position = models.IntegerField(verbose_name='پوزیشن')

    objects = CategoryManager()

    class Meta:
        verbose_name = 'دسته بندی'
        verbose_name_plural = 'دسته بندی ها'
        ordering = ('position',)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.http import HttpResponse, JsonResponse
from django.views import generic
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .models import Article, Category

# def home_view(request, page=1):
#     article_list = Article.objects.published()
#     # page = request.GET.get('page', 1)
#     paginator = Paginator(article_list, 3)
#     try:
#         articles = paginator.page(page)
#     except PageNotAnInteger:
#         articles = paginator.page(1)
#     except EmptyPage:
#         articles = paginator.page(paginator.num_pages)
#
#     context = {
#         'articles': articles,
#         'page_numbers': list(range(1, paginator.num_pages + 1)),
#         'categories': Category.objects.filter(status=True)
#     }
#     return render(request, 'blog/home.html', context)

class ArticleListView(generic.ListView):
    queryset = Article.objects.published()
    template_name = 'blog/article_list.html'
    context_object_name = 'articles'
    paginate_by = 2

    def get_context_data(self, *, object_list=None, **kwargs):
        article_list = Article.objects.published()
        paginator = Paginator(article_list, 3)

        context = super().get_context_data(**kwargs)
        context['page_numbers'] = list(range(1, paginator.num_pages + 1))
        return context

class ArticleDetailView(generic.DetailView):
    template_name = 'blog/article_detail.html'

    def get_object(self, queryset=None):
        return get_object_or_404(Article.objects.published(), slug=self.kwargs.get('slug'))


# def article_detail_view(request, slug):
#     article = get_object_or_404(Article.objects.published(), slug=slug)
#     context = {
#         'article': article,
#     }
#     return render(request, 'blog/article_detail.html', context)

class CategoryListView(generic.ListView):
    template_name = 'blog/category.html'
    context_object_name = 'articles'
    paginate_by = 3

    def get_queryset(self):
        global category
        category = get_object_or_404(Category.objects.published(), slug=self.kwargs.get('slug'), status=True)
        return category.article.published()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = category
        return context

# def category_view(request, slug, page=1):
#     category = get_object_or_404(Category, slug=slug, status=True)
#     category_list = category.article.published()
#     paginator = Paginator(category_list, 2)
#     try:
#         articles = paginator.page(page)
#     except EmptyPage:
#         articles = paginator.page(paginator.num_pages)
#     except PageNotAnInteger:
#         articles = paginator.page(page)
#
#     context = {
#         'articles': articles,
#         'category': category,
#     }
#     return render(request, 'blog/category.html', context)

blog/templates/blog/about.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Clean Blog - Start Bootstrap Theme</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="css/styles.css" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="index.html">Start Bootstrap</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="index.html">Home</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="about.html">About</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="post.html">Sample Post</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="contact.html">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('assets/img/about-bg.jpg')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="page-heading">
                            <h1>About Me</h1>
                            <span class="subheading">This is what I do.</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <main class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequuntur magnam, excepturi aliquid ex itaque esse est vero natus quae optio aperiam soluta voluptatibus corporis atque iste neque sit tempora!</p>
                    </div>
                </div>
            </div>
        </main>
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2022</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>

blog/templates/blog/article_detail.html
{% extends '_base.html' %}
{% load static %}
{% block title %}
    This Is me | {{ article.title }}
{% endblock %}

{% block img %}
    {{ article.thumbnail.url }}
{% endblock %}

{% block body %}
    <header class="masthead" style="background-image:url('{{ article.thumbnail.url }}')">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <div class="site-heading">
                        <h1>{{ article.title |title }}</h1>
                        <time>{{ article.jalali_published }}</time>

                        {#                        <span class="subheading">A Blog Theme by Start Bootstrap</span>#}
                    </div>
                </div>
            </div>
        </div>
    </header>


    <article>
        <div class="container">
            <div class="row">
                <div class="col-lg-8  col-md-10 mx-auto text-justify">
                    {{ article.descriptions|linebreaksbr }}
                </div>
            </div>
        </div>
    </article>


    {#    <div class="container px-4 px-lg-5">#}
    {#        <div class="row gx-4 gx-lg-5 justify-content-center">#}
    {#            <div class="col-md-10 col-lg-8 col-xl-7 text-justify">#}
    {#                <!-- Post preview-->#}
    {#                <div class="row">#}
    {#                    <div class="col-lg-10  col-md-10 mx-auto text-justify">{{ article.descriptions|linebreaksbr }}</div>#}
    {#                </div>#}
    {#                    <p class="post-meta">#}
    {#                        {{ article.jalali_published }}#}
    {#                    </p>#}
    {#                <!-- Divider-->#}
    {#                <hr class="my-4"/>#}
    {##}
    {#                <!-- Pager-->#}
    {#                <div class="d-flex justify-content-end mb-4"><a class="btn btn-primary text-uppercase" href="{% url 'blog:home' %}">Home Page →</a></div>#}
    {#            </div>#}
    {#        </div>#}
    {#    </div>#}


{% endblock %}

blog/templates/blog/article_list.html
{% extends '_base.html' %}
{% load my_tags %}
{% load my_tags %}

{% load static %}

{% block body %}
    <header class="masthead" style="background-image:url('{% static 'blog/assets/img/home-bg.jpg' %}')">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <div class="site-heading">
                        <h1>This is <b>{% ME %}</b></h1>
                        {#                        <span class="subheading">A Blog Theme by Start Bootstrap</span>#}
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Main Content-->
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                {% for article in articles %}
                    <!-- Post preview-->
                    <div class="post-preview">
                        <a href="{% url 'blog:article_detail' article.slug %}">
                            <h2 class="post-title">{{ article.title|safe }}</h2>
                        </a>
                        <h4 class="post-subtitle">{{ article.descriptions|truncatewords:10 }}</h4>
                        {% for cate in article.category_published.all %}
                            <a href="{% url 'blog:category' cate.slug %}"># {{ cate.title }}</a>
                        {% endfor %}


                        <p class="post-meta">
                            {{ article.jalali_published }}
                        </p>
                    </div>
                    <!-- Divider-->
                    <hr class="my-4"/>


                    <!-- Pager-->

                {% endfor %}
                <div class="d-flex justify-content-end mb-4 ">
                    {% if page_obj.has_next %}
                            <a class="btn btn-primary text-uppercase "
                               href="{% url 'blog:home' page_obj.next_page_number %}">→ پست های قدیمی </a>
                    {% endif %}

                    {% if page_obj.has_previous %}
                            <a class="btn btn-primary text-uppercase  me-lg-3" href="{% url 'blog:home' page_obj.previous_page_number %}">
                            &larr; پست های جدید </a>
                    {% endif %}

                </div>
                <nav aria-label="Page navigation example">
                    {% if page_obj.has_other_pages %}
                        <ul class="pagination">
                            {% if page_obj.has_previous %}
                                <li class="page-item"><a class="page-link"
                                                         href="{% url 'blog:home' page_obj.previous_page_number %}">Previous</a>
                                </li>
                            {% endif %}
                            {% for i in page_numbers %}
                                {% if page_obj.number == i %}
                                    <li class="page-item"><a class="page-link" href="#">current</a></li>
                                {% else %}
                                    <li class="page-item"><a class="page-link" href="{% url 'blog:home' i %}">{{ i }}</a></li>
                                {% endif %}
                            {% endfor %}
                            {% if page_obj.has_next %}
                                <li class="page-item"><a class="page-link"
                                                         href="{% url 'blog:home' page_obj.next_page_number %}">Next</a></li>
                            {% endif %}
                        </ul>
                    {% endif %}
                </nav>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/category.html
{% extends '_base.html' %}
{% load my_tags %}
{% load my_tags %}

{% load static %}

{% block body %}
    <header class="masthead" style="background-image:url('{% static 'blog/assets/img/home-bg.jpg' %}')">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <div class="site-heading">
                    <h1>This is <b>{% ME %}</b></h1>
{#                        <span class="subheading">A Blog Theme by Start Bootstrap</span>#}
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Main Content-->
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <h3 class="alert alert-primary text-center">دسته بندی: {{ category.title }}</h3>
            <div class="col-md-10 col-lg-8 col-xl-7">
                {% for article in articles %}
                    <!-- Post preview-->
                    <div class="post-preview">
                        <a href="{% url 'blog:article_detail' article.slug %}">
                            <h2 class="post-title">{{ article.title|safe }}</h2>
                        </a>
                        <h4 class="post-subtitle">{{ article.descriptions|truncatewords:10 }}</h4>
                        {% for cate in article.category.all %}
                            <a href="{% url 'blog:category' cate.slug %}"># {{ cate.title }}</a>
                        {% endfor %}


                        <p class="post-meta">
                            {{ article.jalali_published }}
                        </p>
                    </div>
                    <!-- Divider-->
                    <hr class="my-4"/>


                    <!-- Pager-->

                {% endfor %}
                {% if page_obj.has_next %}
                        <a class="btn btn-primary text-uppercase "
                           href="{% url 'blog:category' category.slug  page_obj.next_page_number %}">→ پست های قدیمی </a>
                {% endif %}

                {% if page_obj.has_previous %}
                        <a class="btn btn-primary text-uppercase  me-lg-3" href="{% url 'blog:category' category.slug  page_obj.previous_page_number %}">
                        &larr; پست های جدید </a>
                {% endif %}


            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/partial/category_loop.html
<ul id=" nav">
    {% for cate in cate.children.published %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:category' cate.slug %}">
                {{ cate.title }}
            </a>
            {% if cate.children.published %}
                {% include 'blog/partial/category_loop.html' %}
            {% endif %}
        </li>
    {% endfor %}
</ul>

blog/templates/blog/partial/category_nav.html
<div id="container">
    <ul class="nav">
        <li >
            <a  href="{% url 'blog:home' %}">خانه </a>
        </li>
        {% for cate in categories %}
            {% if cate.parent == None %}
                <li >
                <a  href="{% url 'blog:category' cate.slug %}">
                    {{ cate }}
                </a>
                {% if cate.children.published %}
                    {% include 'blog/partial/category_loop.html' %}
                {% endif %}
            {% endif %}
        {% endfor %}
    </ul>
</div>

blog/templates/blog/post.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Clean Blog - Start Bootstrap Theme</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="css/styles.css" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="index.html">Start Bootstrap</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="index.html">Home</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="about.html">About</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="post.html">Sample Post</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="contact.html">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('assets/img/post-bg.jpg')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="post-heading">
                            <h1>Man must explore, and this is exploration at its greatest</h1>
                            <h2 class="subheading">Problems look mighty small from 150 miles up</h2>
                            <span class="meta">
                                Posted by
                                <a href="#!">Start Bootstrap</a>
                                on August 24, 2022
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Post Content-->
        <article class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <p>Never in all their history have men been able truly to conceive of the world as one: a single sphere, a globe, having the qualities of a globe, a round earth in which all the directions eventually meet, in which there is no center because every point, or none, is center — an equal earth which all men occupy as equals. The airman's earth, if free men make it, will be truly round: a globe in practice, not in theory.</p>
                        <p>Science cuts two ways, of course; its products can be used for both good and evil. But there's no turning back from science. The early warnings about technological dangers also come from science.</p>
                        <p>What was most significant about the lunar voyage was not that man set foot on the Moon but that they set eye on the earth.</p>
                        <p>A Chinese tale tells of some men sent to harm a young girl who, upon seeing her beauty, become her protectors rather than her violators. That's how I felt seeing the Earth for the first time. I could not help but love and cherish her.</p>
                        <p>For those who have seen the Earth from space, and for the hundreds and perhaps thousands more who will, the experience most certainly changes your perspective. The things that we share in our world are far more valuable than those which divide us.</p>
                        <h2 class="section-heading">The Final Frontier</h2>
                        <p>There can be no thought of finishing for ‘aiming for the stars.’ Both figuratively and literally, it is a task to occupy the generations. And no matter how much progress one makes, there is always the thrill of just beginning.</p>
                        <p>There can be no thought of finishing for ‘aiming for the stars.’ Both figuratively and literally, it is a task to occupy the generations. And no matter how much progress one makes, there is always the thrill of just beginning.</p>
                        <blockquote class="blockquote">The dreams of yesterday are the hopes of today and the reality of tomorrow. Science has not yet mastered prophecy. We predict too much for the next year and yet far too little for the next ten.</blockquote>
                        <p>Spaceflights cannot be stopped. This is not the work of any one man or even a group of men. It is a historical process which mankind is carrying out in accordance with the natural laws of human development.</p>
                        <h2 class="section-heading">Reaching for the Stars</h2>
                        <p>As we got further and further away, it [the Earth] diminished in size. Finally it shrank to the size of a marble, the most beautiful you can imagine. That beautiful, warm, living object looked so fragile, so delicate, that if you touched it with a finger it would crumble and fall apart. Seeing this has to change a man.</p>
                        <a href="#!"><img class="img-fluid" src="assets/img/post-sample-image.jpg" alt="..." /></a>
                        <span class="caption text-muted">To go places and do things that have never been done before – that’s what living is all about.</span>
                        <p>Space, the final frontier. These are the voyages of the Starship Enterprise. Its five-year mission: to explore strange new worlds, to seek out new life and new civilizations, to boldly go where no man has gone before.</p>
                        <p>As I stand out here in the wonders of the unknown at Hadley, I sort of realize there’s a fundamental truth to our nature, Man must explore, and this is exploration at its greatest.</p>
                        <p>
                            Placeholder text by
                            <a href="http://spaceipsum.com/">Space Ipsum</a>
                            &middot; Images by
                            <a href="https://www.flickr.com/photos/nasacommons/">NASA on The Commons</a>
                        </p>
                    </div>
                </div>
            </div>
        </article>
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2022</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>